// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/demurrage/v1/demurrage.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the governance-controlled parameters of the x/demurrage module.
// The naming mirrors x/mint intentionally so that governance ergonomics are familiar.
type Params struct {
	// demurrage_rate_min is the floor of the annualised demurrage rate (e.g. 0.07 = 7%).
	DemurrageRateMin cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=demurrage_rate_min,json=demurrageRateMin,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"demurrage_rate_min"`
	// demurrage_rate_max is the ceiling of the annualised demurrage rate (e.g. 0.20 = 20%).
	DemurrageRateMax cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=demurrage_rate_max,json=demurrageRateMax,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"demurrage_rate_max"`
	// demurrage_rate_change is the maximum yearly change in the demurrage rate (e.g. 0.13 = 13%).
	DemurrageRateChange cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=demurrage_rate_change,json=demurrageRateChange,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"demurrage_rate_change"`
	// goal_bonded is the target bonding ratio (e.g. 0.67 = 67%).
	GoalBonded cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=goal_bonded,json=goalBonded,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"goal_bonded"`
	// epoch_identifier is the x/epochs epoch identifier to hook into (e.g. "hour").
	EpochIdentifier string `protobuf:"bytes,5,opt,name=epoch_identifier,json=epochIdentifier,proto3" json:"epoch_identifier,omitempty"`
	// sink_mode controls where levied tokens go: "burn", "community_pool", or "redistribution".
	SinkMode string `protobuf:"bytes,6,opt,name=sink_mode,json=sinkMode,proto3" json:"sink_mode,omitempty"`
	// exempt_module_accounts is the list of module-account names whose balances are never levied.
	// Always includes bonded_tokens_pool and not_bonded_tokens_pool; others (gov, distribution,
	// community_pool, ibc_transfer) should be added here.
	ExemptModuleAccounts []string `protobuf:"bytes,7,rep,name=exempt_module_accounts,json=exemptModuleAccounts,proto3" json:"exempt_module_accounts,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b750d6ce4d626e2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEpochIdentifier() string {
	if m != nil {
		return m.EpochIdentifier
	}
	return ""
}

func (m *Params) GetSinkMode() string {
	if m != nil {
		return m.SinkMode
	}
	return ""
}

func (m *Params) GetExemptModuleAccounts() []string {
	if m != nil {
		return m.ExemptModuleAccounts
	}
	return nil
}

// DemurrageState holds the module-level dynamic state persisted each epoch.
type DemurrageState struct {
	// current_annual_rate is the current annualised demurrage rate as a sdk.Dec string.
	CurrentAnnualRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=current_annual_rate,json=currentAnnualRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"current_annual_rate"`
	// global_accumulator is the running product (1 - per_epoch_rate) applied each epoch.
	// Starts at 1.0 at genesis and is monotonically non-increasing.
	GlobalAccumulator cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=global_accumulator,json=globalAccumulator,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"global_accumulator"`
}

func (m *DemurrageState) Reset()         { *m = DemurrageState{} }
func (m *DemurrageState) String() string { return proto.CompactTextString(m) }
func (*DemurrageState) ProtoMessage()    {}
func (*DemurrageState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b750d6ce4d626e2, []int{1}
}
func (m *DemurrageState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DemurrageState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DemurrageState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DemurrageState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemurrageState.Merge(m, src)
}
func (m *DemurrageState) XXX_Size() int {
	return m.Size()
}
func (m *DemurrageState) XXX_DiscardUnknown() {
	xxx_messageInfo_DemurrageState.DiscardUnknown(m)
}

var xxx_messageInfo_DemurrageState proto.InternalMessageInfo

// AccountDemurrageState holds the per-account lazy-evaluation state.
// Stored in x/demurrage's own KV store, keyed by account address.
type AccountDemurrageState struct {
	// reference_accumulator is the value of GlobalAccumulator the last time this
	// account's balance was materialised (touched). Used to compute accrued levy.
	ReferenceAccumulator cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=reference_accumulator,json=referenceAccumulator,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reference_accumulator"`
	// reference_block is the block height at which reference_accumulator was last recorded.
	// Informational only — not used in levy calculations.
	ReferenceBlock int64 `protobuf:"varint,2,opt,name=reference_block,json=referenceBlock,proto3" json:"reference_block,omitempty"`
}

func (m *AccountDemurrageState) Reset()         { *m = AccountDemurrageState{} }
func (m *AccountDemurrageState) String() string { return proto.CompactTextString(m) }
func (*AccountDemurrageState) ProtoMessage()    {}
func (*AccountDemurrageState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b750d6ce4d626e2, []int{2}
}
func (m *AccountDemurrageState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountDemurrageState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountDemurrageState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountDemurrageState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDemurrageState.Merge(m, src)
}
func (m *AccountDemurrageState) XXX_Size() int {
	return m.Size()
}
func (m *AccountDemurrageState) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDemurrageState.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDemurrageState proto.InternalMessageInfo

func (m *AccountDemurrageState) GetReferenceBlock() int64 {
	if m != nil {
		return m.ReferenceBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.demurrage.v1.Params")
	proto.RegisterType((*DemurrageState)(nil), "cosmos.demurrage.v1.DemurrageState")
	proto.RegisterType((*AccountDemurrageState)(nil), "cosmos.demurrage.v1.AccountDemurrageState")
}

func init() {
	proto.RegisterFile("cosmos/demurrage/v1/demurrage.proto", fileDescriptor_7b750d6ce4d626e2)
}

var fileDescriptor_7b750d6ce4d626e2 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0x63, 0x5a, 0x02, 0x39, 0xa4, 0xfe, 0xb9, 0x24, 0xc8, 0xb4, 0xc2, 0xad, 0xc2, 0x40,
	0xa9, 0x54, 0x5b, 0x11, 0x88, 0x81, 0x2d, 0x21, 0x03, 0x48, 0x44, 0x42, 0x66, 0x40, 0x62, 0x31,
	0x97, 0xf3, 0x1b, 0xc7, 0xc4, 0x77, 0x17, 0x9d, 0xcf, 0x55, 0xfa, 0x15, 0x98, 0xf8, 0x18, 0x1d,
	0x3b, 0xb0, 0xf1, 0x05, 0x3a, 0x56, 0x48, 0x48, 0x88, 0xa1, 0x42, 0xc9, 0xd0, 0xaf, 0x81, 0x7c,
	0x67, 0x9c, 0xb6, 0x82, 0x81, 0x96, 0x25, 0x8a, 0x9f, 0xe7, 0xf5, 0xef, 0xb9, 0xf7, 0xf5, 0xab,
	0x43, 0x0f, 0xa8, 0x48, 0x99, 0x48, 0xbd, 0x10, 0x58, 0x26, 0x25, 0x89, 0xc0, 0xdb, 0x6f, 0x2f,
	0x1e, 0xdc, 0x89, 0x14, 0x4a, 0xe0, 0xba, 0x29, 0x72, 0x17, 0xfa, 0x7e, 0x7b, 0xa3, 0x11, 0x89,
	0x48, 0x68, 0xdf, 0xcb, 0xff, 0x99, 0xd2, 0x8d, 0x7b, 0xa6, 0x34, 0x30, 0x46, 0xf1, 0x9e, 0xb1,
	0xd6, 0x09, 0x8b, 0xb9, 0xf0, 0xf4, 0xaf, 0x91, 0x5a, 0x5f, 0x96, 0x51, 0xf5, 0x35, 0x91, 0x84,
	0xa5, 0x38, 0x44, 0xb8, 0xc4, 0x07, 0x92, 0x28, 0x08, 0x58, 0xcc, 0x6d, 0x6b, 0xdb, 0xda, 0xa9,
	0x75, 0x9f, 0x1e, 0x9f, 0x6e, 0x55, 0x7e, 0x9c, 0x6e, 0x6d, 0x1a, 0x5e, 0x1a, 0x8e, 0xdd, 0x58,
	0x78, 0x8c, 0xa8, 0x91, 0xfb, 0x0a, 0x22, 0x42, 0x0f, 0x7a, 0x40, 0xbf, 0x7e, 0xde, 0x43, 0x45,
	0x5c, 0x0f, 0xe8, 0xe1, 0xd9, 0xd1, 0xae, 0xe5, 0xaf, 0x95, 0x44, 0x9f, 0x28, 0xe8, 0xc7, 0xfc,
	0x4f, 0x29, 0x64, 0x6a, 0xdf, 0xf8, 0x9f, 0x29, 0x64, 0x8a, 0x3f, 0xa0, 0xe6, 0xa5, 0x14, 0x3a,
	0x22, 0x3c, 0x02, 0x7b, 0xe9, 0x5a, 0x41, 0xf5, 0x0b, 0x41, 0xcf, 0x35, 0x12, 0xbf, 0x45, 0x77,
	0x22, 0x41, 0x92, 0x60, 0x20, 0x78, 0x08, 0xa1, 0xbd, 0x7c, 0xad, 0x04, 0x94, 0xa3, 0xba, 0x9a,
	0x84, 0x1f, 0xa1, 0x35, 0x98, 0x08, 0x3a, 0x0a, 0xe2, 0x10, 0xb8, 0x8a, 0x87, 0x31, 0x48, 0xfb,
	0x66, 0x4e, 0xf7, 0x57, 0xb5, 0xfe, 0xb2, 0x94, 0xf1, 0x26, 0xaa, 0xa5, 0x31, 0x1f, 0x07, 0x4c,
	0x84, 0x60, 0x57, 0x75, 0xcd, 0xed, 0x5c, 0xe8, 0x8b, 0x10, 0xf0, 0x13, 0x74, 0x17, 0xa6, 0xc0,
	0x26, 0x2a, 0xb7, 0xb3, 0x04, 0x02, 0x42, 0xa9, 0xc8, 0xb8, 0x4a, 0xed, 0x5b, 0xdb, 0x4b, 0x3b,
	0x35, 0xbf, 0x61, 0xdc, 0xbe, 0x36, 0x3b, 0x85, 0xf7, 0xac, 0xf5, 0xf1, 0xec, 0x68, 0xf7, 0xbe,
	0x39, 0xdf, 0x5e, 0x1a, 0x8e, 0xbd, 0xe9, 0xb9, 0x15, 0x35, 0x2b, 0xd3, 0xfa, 0x66, 0xa1, 0x95,
	0xde, 0x6f, 0xf1, 0x8d, 0x22, 0x0a, 0x30, 0x41, 0x75, 0x9a, 0x49, 0x09, 0x5c, 0x05, 0x84, 0xf3,
	0x8c, 0x24, 0x7a, 0xfc, 0xc5, 0x1a, 0xb5, 0xff, 0x79, 0x2a, 0xfe, 0x7a, 0x41, 0xeb, 0x68, 0x58,
	0x3e, 0x76, 0xfc, 0x1e, 0xe1, 0x28, 0x11, 0x03, 0x92, 0xe4, 0x8d, 0x64, 0x2c, 0x4b, 0x88, 0x12,
	0xb2, 0x58, 0xa1, 0xab, 0x24, 0x18, 0x58, 0x67, 0xc1, 0x6a, 0x1d, 0x5a, 0xa8, 0x59, 0x0c, 0xe2,
	0x52, 0x7b, 0x43, 0xd4, 0x94, 0x30, 0x04, 0x09, 0x9c, 0xc2, 0x85, 0xf8, 0x2b, 0x37, 0xd8, 0x28,
	0x79, 0xe7, 0x4e, 0x80, 0x1f, 0xa2, 0xd5, 0x45, 0xce, 0x20, 0x11, 0x74, 0xac, 0x1b, 0x5c, 0xf2,
	0x57, 0x4a, 0xb9, 0x9b, 0xab, 0xdd, 0x17, 0xc7, 0x33, 0xc7, 0x3a, 0x99, 0x39, 0xd6, 0xcf, 0x99,
	0x63, 0x7d, 0x9a, 0x3b, 0x95, 0x93, 0xb9, 0x53, 0xf9, 0x3e, 0x77, 0x2a, 0xef, 0xdc, 0x28, 0x56,
	0xa3, 0x6c, 0xe0, 0x52, 0xc1, 0x8a, 0x6b, 0xc0, 0xfb, 0xcb, 0xd7, 0x54, 0x07, 0x13, 0x48, 0x07,
	0x55, 0x7d, 0x23, 0x3c, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x00, 0x5c, 0xe3, 0x27, 0x91, 0x04,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExemptModuleAccounts) > 0 {
		for iNdEx := len(m.ExemptModuleAccounts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ExemptModuleAccounts[iNdEx])
			copy(dAtA[i:], m.ExemptModuleAccounts[iNdEx])
			i = encodeVarintDemurrage(dAtA, i, uint64(len(m.ExemptModuleAccounts[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.SinkMode) > 0 {
		i -= len(m.SinkMode)
		copy(dAtA[i:], m.SinkMode)
		i = encodeVarintDemurrage(dAtA, i, uint64(len(m.SinkMode)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EpochIdentifier) > 0 {
		i -= len(m.EpochIdentifier)
		copy(dAtA[i:], m.EpochIdentifier)
		i = encodeVarintDemurrage(dAtA, i, uint64(len(m.EpochIdentifier)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.GoalBonded.Size()
		i -= size
		if _, err := m.GoalBonded.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.DemurrageRateChange.Size()
		i -= size
		if _, err := m.DemurrageRateChange.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.DemurrageRateMax.Size()
		i -= size
		if _, err := m.DemurrageRateMax.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.DemurrageRateMin.Size()
		i -= size
		if _, err := m.DemurrageRateMin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *DemurrageState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DemurrageState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DemurrageState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.GlobalAccumulator.Size()
		i -= size
		if _, err := m.GlobalAccumulator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.CurrentAnnualRate.Size()
		i -= size
		if _, err := m.CurrentAnnualRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AccountDemurrageState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountDemurrageState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountDemurrageState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReferenceBlock != 0 {
		i = encodeVarintDemurrage(dAtA, i, uint64(m.ReferenceBlock))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.ReferenceAccumulator.Size()
		i -= size
		if _, err := m.ReferenceAccumulator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDemurrage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintDemurrage(dAtA []byte, offset int, v uint64) int {
	offset -= sovDemurrage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DemurrageRateMin.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	l = m.DemurrageRateMax.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	l = m.DemurrageRateChange.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	l = m.GoalBonded.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	l = len(m.EpochIdentifier)
	if l > 0 {
		n += 1 + l + sovDemurrage(uint64(l))
	}
	l = len(m.SinkMode)
	if l > 0 {
		n += 1 + l + sovDemurrage(uint64(l))
	}
	if len(m.ExemptModuleAccounts) > 0 {
		for _, s := range m.ExemptModuleAccounts {
			l = len(s)
			n += 1 + l + sovDemurrage(uint64(l))
		}
	}
	return n
}

func (m *DemurrageState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CurrentAnnualRate.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	l = m.GlobalAccumulator.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	return n
}

func (m *AccountDemurrageState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ReferenceAccumulator.Size()
	n += 1 + l + sovDemurrage(uint64(l))
	if m.ReferenceBlock != 0 {
		n += 1 + sovDemurrage(uint64(m.ReferenceBlock))
	}
	return n
}

func sovDemurrage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDemurrage(x uint64) (n int) {
	return sovDemurrage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemurrage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemurrageRateMin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DemurrageRateMin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemurrageRateMax", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DemurrageRateMax.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemurrageRateChange", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DemurrageRateChange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoalBonded", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GoalBonded.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SinkMode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SinkMode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExemptModuleAccounts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExemptModuleAccounts = append(m.ExemptModuleAccounts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDemurrage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemurrage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DemurrageState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemurrage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DemurrageState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DemurrageState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentAnnualRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentAnnualRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalAccumulator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GlobalAccumulator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDemurrage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemurrage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountDemurrageState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemurrage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountDemurrageState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountDemurrageState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferenceAccumulator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemurrage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemurrage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReferenceAccumulator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferenceBlock", wireType)
			}
			m.ReferenceBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferenceBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDemurrage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemurrage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDemurrage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDemurrage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDemurrage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDemurrage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDemurrage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDemurrage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDemurrage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDemurrage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDemurrage = fmt.Errorf("proto: unexpected end of group")
)
