// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/demurrage/v1/events.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventDemurrageEpoch is emitted once per epoch when the global accumulator is updated.
type EventDemurrageEpoch struct {
	AnnualRate        cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=annual_rate,json=annualRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"annual_rate"`
	PerEpochRate      cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=per_epoch_rate,json=perEpochRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"per_epoch_rate"`
	GlobalAccumulator cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=global_accumulator,json=globalAccumulator,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"global_accumulator"`
	BondingRatio      cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=bonding_ratio,json=bondingRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"bonding_ratio"`
	EpochNumber       int64                       `protobuf:"varint,5,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
}

func (m *EventDemurrageEpoch) Reset()         { *m = EventDemurrageEpoch{} }
func (m *EventDemurrageEpoch) String() string { return proto.CompactTextString(m) }
func (*EventDemurrageEpoch) ProtoMessage()    {}
func (*EventDemurrageEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4943a866c7bb04c, []int{0}
}
func (m *EventDemurrageEpoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDemurrageEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDemurrageEpoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDemurrageEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDemurrageEpoch.Merge(m, src)
}
func (m *EventDemurrageEpoch) XXX_Size() int {
	return m.Size()
}
func (m *EventDemurrageEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDemurrageEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_EventDemurrageEpoch proto.InternalMessageInfo

func (m *EventDemurrageEpoch) GetEpochNumber() int64 {
	if m != nil {
		return m.EpochNumber
	}
	return 0
}

// EventDemurrageApplied is emitted when an account's balance is materialised (levy collected).
type EventDemurrageApplied struct {
	Account      string                `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AmountLevied cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount_levied,json=amountLevied,proto3,customtype=cosmossdk.io/math.Int" json:"amount_levied"`
	NewBalance   cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=new_balance,json=newBalance,proto3,customtype=cosmossdk.io/math.Int" json:"new_balance"`
}

func (m *EventDemurrageApplied) Reset()         { *m = EventDemurrageApplied{} }
func (m *EventDemurrageApplied) String() string { return proto.CompactTextString(m) }
func (*EventDemurrageApplied) ProtoMessage()    {}
func (*EventDemurrageApplied) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4943a866c7bb04c, []int{1}
}
func (m *EventDemurrageApplied) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDemurrageApplied) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDemurrageApplied.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDemurrageApplied) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDemurrageApplied.Merge(m, src)
}
func (m *EventDemurrageApplied) XXX_Size() int {
	return m.Size()
}
func (m *EventDemurrageApplied) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDemurrageApplied.DiscardUnknown(m)
}

var xxx_messageInfo_EventDemurrageApplied proto.InternalMessageInfo

func (m *EventDemurrageApplied) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func init() {
	proto.RegisterType((*EventDemurrageEpoch)(nil), "cosmos.demurrage.v1.EventDemurrageEpoch")
	proto.RegisterType((*EventDemurrageApplied)(nil), "cosmos.demurrage.v1.EventDemurrageApplied")
}

func init() { proto.RegisterFile("cosmos/demurrage/v1/events.proto", fileDescriptor_a4943a866c7bb04c) }

var fileDescriptor_a4943a866c7bb04c = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x13, 0xeb, 0x1f, 0x9c, 0xf6, 0x0a, 0xce, 0xf5, 0x42, 0xbc, 0x42, 0x5a, 0xbb, 0x2a,
	0x48, 0x13, 0x8a, 0x4f, 0xd0, 0xd2, 0x82, 0x85, 0x22, 0x92, 0x85, 0x82, 0x9b, 0x38, 0x99, 0x1c,
	0xd2, 0xd0, 0x64, 0x26, 0x4c, 0x26, 0xa9, 0x7d, 0x0b, 0xdf, 0xc0, 0x97, 0xf0, 0x21, 0xba, 0xac,
	0xae, 0xc4, 0x45, 0x91, 0xf6, 0x45, 0x24, 0x33, 0x53, 0xad, 0xb8, 0xb2, 0xab, 0xcc, 0x7c, 0x7c,
	0xf9, 0x9d, 0x8f, 0x73, 0xce, 0xa0, 0x1e, 0xe5, 0x65, 0xce, 0x4b, 0x3f, 0x86, 0xbc, 0x12, 0x82,
	0x24, 0xe0, 0xd7, 0x23, 0x1f, 0x6a, 0x60, 0xb2, 0xf4, 0x0a, 0xc1, 0x25, 0xc7, 0xd7, 0xda, 0xe1,
	0xfd, 0x76, 0x78, 0xf5, 0xe8, 0xf6, 0xa9, 0x16, 0x43, 0x65, 0xf1, 0x8d, 0x43, 0x5d, 0x6e, 0x9f,
	0x24, 0x3c, 0xe1, 0x5a, 0x6f, 0x4e, 0x5a, 0xed, 0x7f, 0x6e, 0xa1, 0xeb, 0x59, 0x83, 0x9d, 0x9e,
	0x30, 0xb3, 0x82, 0xd3, 0x25, 0x0e, 0x50, 0x9b, 0x30, 0x56, 0x91, 0x2c, 0x14, 0x44, 0x82, 0x63,
	0xf7, 0xec, 0xc1, 0xc3, 0xc9, 0x68, 0xbb, 0xef, 0x5a, 0x3f, 0xf6, 0xdd, 0x67, 0x1a, 0x5c, 0xc6,
	0x2b, 0x2f, 0xe5, 0x7e, 0x4e, 0xe4, 0xd2, 0x5b, 0x40, 0x42, 0xe8, 0x66, 0x0a, 0xf4, 0xdb, 0x97,
	0x21, 0x32, 0x75, 0xa7, 0x40, 0x03, 0xa4, 0x29, 0x01, 0x91, 0x80, 0xdf, 0xa1, 0x47, 0x05, 0x88,
	0x10, 0x9a, 0x02, 0x1a, 0x7b, 0xe7, 0x52, 0x6c, 0xa7, 0x00, 0xa1, 0x82, 0x2a, 0xf0, 0x07, 0x84,
	0x93, 0x8c, 0x47, 0x24, 0x0b, 0x09, 0xa5, 0x55, 0x5e, 0x65, 0x44, 0x72, 0xe1, 0xb4, 0x2e, 0x85,
	0x3f, 0xd6, 0xb0, 0xf1, 0x1f, 0x16, 0x7e, 0x8b, 0xae, 0x22, 0xce, 0xe2, 0x94, 0x25, 0x4d, 0xf0,
	0x94, 0x3b, 0x77, 0x2f, 0x4e, 0x6e, 0x38, 0x41, 0x83, 0xc1, 0xcf, 0x51, 0x47, 0xb7, 0x83, 0x55,
	0x79, 0x04, 0xc2, 0xb9, 0xd7, 0xb3, 0x07, 0xad, 0xa0, 0xad, 0xb4, 0xd7, 0x4a, 0xea, 0x7f, 0xb5,
	0xd1, 0xcd, 0xdf, 0x13, 0x1a, 0x17, 0x45, 0x96, 0x42, 0x8c, 0x1d, 0xf4, 0x80, 0x50, 0xca, 0x2b,
	0x26, 0xf5, 0x7c, 0x82, 0xd3, 0x15, 0xbf, 0x41, 0x57, 0x24, 0x6f, 0x4e, 0x61, 0x06, 0x75, 0x0a,
	0xb1, 0x69, 0xf4, 0x0b, 0x13, 0xf7, 0xe6, 0xdf, 0xb8, 0x73, 0x26, 0xcf, 0x82, 0xce, 0x99, 0x0c,
	0x3a, 0x9a, 0xb0, 0x50, 0x00, 0xbc, 0x40, 0x6d, 0x06, 0xeb, 0x30, 0x22, 0x19, 0x61, 0x14, 0x4c,
	0x6f, 0xff, 0x8b, 0x87, 0x18, 0xac, 0x27, 0xfa, 0xf7, 0xc9, 0xab, 0xed, 0xc1, 0xb5, 0x77, 0x07,
	0xd7, 0xfe, 0x79, 0x70, 0xed, 0x4f, 0x47, 0xd7, 0xda, 0x1d, 0x5d, 0xeb, 0xfb, 0xd1, 0xb5, 0xde,
	0x7b, 0x49, 0x2a, 0x97, 0x55, 0xe4, 0x51, 0x9e, 0x9b, 0xf5, 0x35, 0x9f, 0x61, 0x19, 0xaf, 0xfc,
	0x8f, 0x67, 0xef, 0x41, 0x6e, 0x0a, 0x28, 0xa3, 0xfb, 0x6a, 0x8d, 0x5f, 0xfe, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x46, 0xd0, 0x97, 0x30, 0x03, 0x00, 0x00,
}

func (m *EventDemurrageEpoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDemurrageEpoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDemurrageEpoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochNumber != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.EpochNumber))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.BondingRatio.Size()
		i -= size
		if _, err := m.BondingRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.GlobalAccumulator.Size()
		i -= size
		if _, err := m.GlobalAccumulator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PerEpochRate.Size()
		i -= size
		if _, err := m.PerEpochRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.AnnualRate.Size()
		i -= size
		if _, err := m.AnnualRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventDemurrageApplied) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDemurrageApplied) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDemurrageApplied) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.NewBalance.Size()
		i -= size
		if _, err := m.NewBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.AmountLevied.Size()
		i -= size
		if _, err := m.AmountLevied.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventDemurrageEpoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AnnualRate.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.PerEpochRate.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.GlobalAccumulator.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.BondingRatio.Size()
	n += 1 + l + sovEvents(uint64(l))
	if m.EpochNumber != 0 {
		n += 1 + sovEvents(uint64(m.EpochNumber))
	}
	return n
}

func (m *EventDemurrageApplied) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = m.AmountLevied.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.NewBalance.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventDemurrageEpoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDemurrageEpoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDemurrageEpoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnnualRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AnnualRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerEpochRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PerEpochRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalAccumulator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GlobalAccumulator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondingRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNumber", wireType)
			}
			m.EpochNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNumber |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDemurrageApplied) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDemurrageApplied: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDemurrageApplied: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountLevied", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountLevied.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
