// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/demurrage/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9aa3714f3f299a2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9aa3714f3f299a2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryDemurrageStateRequest is the request type for the Query/DemurrageState RPC method.
type QueryDemurrageStateRequest struct {
}

func (m *QueryDemurrageStateRequest) Reset()         { *m = QueryDemurrageStateRequest{} }
func (m *QueryDemurrageStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDemurrageStateRequest) ProtoMessage()    {}
func (*QueryDemurrageStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9aa3714f3f299a2, []int{2}
}
func (m *QueryDemurrageStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDemurrageStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDemurrageStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDemurrageStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDemurrageStateRequest.Merge(m, src)
}
func (m *QueryDemurrageStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDemurrageStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDemurrageStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDemurrageStateRequest proto.InternalMessageInfo

// QueryDemurrageStateResponse is the response type for the Query/DemurrageState RPC method.
type QueryDemurrageStateResponse struct {
	State DemurrageState `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
}

func (m *QueryDemurrageStateResponse) Reset()         { *m = QueryDemurrageStateResponse{} }
func (m *QueryDemurrageStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDemurrageStateResponse) ProtoMessage()    {}
func (*QueryDemurrageStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9aa3714f3f299a2, []int{3}
}
func (m *QueryDemurrageStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDemurrageStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDemurrageStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDemurrageStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDemurrageStateResponse.Merge(m, src)
}
func (m *QueryDemurrageStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDemurrageStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDemurrageStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDemurrageStateResponse proto.InternalMessageInfo

func (m *QueryDemurrageStateResponse) GetState() DemurrageState {
	if m != nil {
		return m.State
	}
	return DemurrageState{}
}

// QueryEffectiveBalanceRequest is the request type for the Query/EffectiveBalance RPC method.
type QueryEffectiveBalanceRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryEffectiveBalanceRequest) Reset()         { *m = QueryEffectiveBalanceRequest{} }
func (m *QueryEffectiveBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEffectiveBalanceRequest) ProtoMessage()    {}
func (*QueryEffectiveBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9aa3714f3f299a2, []int{4}
}
func (m *QueryEffectiveBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEffectiveBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEffectiveBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEffectiveBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEffectiveBalanceRequest.Merge(m, src)
}
func (m *QueryEffectiveBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEffectiveBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEffectiveBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEffectiveBalanceRequest proto.InternalMessageInfo

func (m *QueryEffectiveBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryEffectiveBalanceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryEffectiveBalanceResponse is the response type for the Query/EffectiveBalance RPC method.
type QueryEffectiveBalanceResponse struct {
	// effective_balance is the post-demurrage balance (what the account would have
	// if materialised right now). This is a read-only projection; it does NOT
	// modify chain state.
	EffectiveBalance cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=effective_balance,json=effectiveBalance,proto3,customtype=cosmossdk.io/math.Int" json:"effective_balance"`
}

func (m *QueryEffectiveBalanceResponse) Reset()         { *m = QueryEffectiveBalanceResponse{} }
func (m *QueryEffectiveBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEffectiveBalanceResponse) ProtoMessage()    {}
func (*QueryEffectiveBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9aa3714f3f299a2, []int{5}
}
func (m *QueryEffectiveBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEffectiveBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEffectiveBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEffectiveBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEffectiveBalanceResponse.Merge(m, src)
}
func (m *QueryEffectiveBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEffectiveBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEffectiveBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEffectiveBalanceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.demurrage.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.demurrage.v1.QueryParamsResponse")
	proto.RegisterType((*QueryDemurrageStateRequest)(nil), "cosmos.demurrage.v1.QueryDemurrageStateRequest")
	proto.RegisterType((*QueryDemurrageStateResponse)(nil), "cosmos.demurrage.v1.QueryDemurrageStateResponse")
	proto.RegisterType((*QueryEffectiveBalanceRequest)(nil), "cosmos.demurrage.v1.QueryEffectiveBalanceRequest")
	proto.RegisterType((*QueryEffectiveBalanceResponse)(nil), "cosmos.demurrage.v1.QueryEffectiveBalanceResponse")
}

func init() { proto.RegisterFile("cosmos/demurrage/v1/query.proto", fileDescriptor_f9aa3714f3f299a2) }

var fileDescriptor_f9aa3714f3f299a2 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0x56, 0x12, 0xe9, 0x08, 0xd2, 0x4e, 0x23, 0xc4, 0x4d, 0xba, 0x91, 0xcd, 0xc1, 0xa2,
	0x74, 0xc7, 0xc4, 0x8b, 0x78, 0x10, 0x09, 0x15, 0xec, 0x45, 0x34, 0x22, 0x88, 0x97, 0x32, 0xd9,
	0x9d, 0x6e, 0x97, 0x76, 0x67, 0xb6, 0x3b, 0x93, 0x60, 0x28, 0x05, 0xf1, 0x17, 0x08, 0x1e, 0xfc,
	0x0b, 0x1e, 0x3d, 0x78, 0xf3, 0x0f, 0xf4, 0x58, 0xf4, 0x22, 0x1e, 0x8a, 0x24, 0x82, 0x7f, 0x43,
	0x32, 0x6f, 0x56, 0x9b, 0x76, 0x82, 0x7a, 0xd9, 0xdd, 0x79, 0xef, 0x7b, 0xef, 0xfb, 0xde, 0xbc,
	0x6f, 0x51, 0x33, 0x14, 0x32, 0x15, 0x92, 0x44, 0x2c, 0x1d, 0xe4, 0x39, 0x8d, 0x19, 0x19, 0xb6,
	0xc9, 0xfe, 0x80, 0xe5, 0xa3, 0x20, 0xcb, 0x85, 0x12, 0x78, 0x05, 0x00, 0xc1, 0x6f, 0x40, 0x30,
	0x6c, 0xbb, 0xd5, 0x58, 0xc4, 0x42, 0xe7, 0xc9, 0xf4, 0x0b, 0xa0, 0x6e, 0x23, 0x16, 0x22, 0xde,
	0x63, 0x84, 0x66, 0x09, 0xa1, 0x9c, 0x0b, 0x45, 0x55, 0x22, 0xb8, 0x34, 0xd9, 0x96, 0x8d, 0xe9,
	0x4f, 0x57, 0x00, 0x5d, 0x05, 0xd0, 0x16, 0xf4, 0x36, 0xd4, 0x90, 0x5a, 0xa6, 0x69, 0xc2, 0x05,
	0xd1, 0x4f, 0x08, 0xf9, 0x55, 0x84, 0x9f, 0x4c, 0xa5, 0x3e, 0xa6, 0x39, 0x4d, 0x65, 0x8f, 0xed,
	0x0f, 0x98, 0x54, 0xfe, 0x33, 0xb4, 0x32, 0x13, 0x95, 0x99, 0xe0, 0x92, 0xe1, 0x7b, 0xa8, 0x92,
	0xe9, 0x48, 0xcd, 0xb9, 0xe6, 0xac, 0x5d, 0xea, 0xd4, 0x03, 0xcb, 0x64, 0x01, 0x14, 0x75, 0x17,
	0x8f, 0x4e, 0x9a, 0xa5, 0xf7, 0x3f, 0x3f, 0xdc, 0x70, 0x7a, 0xa6, 0xca, 0x6f, 0x20, 0x57, 0xb7,
	0xdd, 0x28, 0xe0, 0x4f, 0x15, 0x55, 0xac, 0x20, 0x0d, 0x51, 0xdd, 0x9a, 0x35, 0xe4, 0x1b, 0xa8,
	0x2c, 0xa7, 0x01, 0xc3, 0xdd, 0xb2, 0x72, 0xcf, 0xd6, 0x9e, 0xd6, 0x00, 0xc5, 0xfe, 0x23, 0xd4,
	0xd0, 0x24, 0x0f, 0xb6, 0xb7, 0x59, 0xa8, 0x92, 0x21, 0xeb, 0xd2, 0x3d, 0xca, 0xc3, 0x42, 0x04,
	0xae, 0xa1, 0x8b, 0x34, 0x8a, 0x72, 0x26, 0x61, 0xc6, 0xc5, 0x5e, 0x71, 0xc4, 0x55, 0x54, 0x8e,
	0x18, 0x17, 0x69, 0x6d, 0x41, 0xc7, 0xe1, 0xe0, 0x8f, 0xd0, 0xea, 0x9c, 0x7e, 0x46, 0xf6, 0x73,
	0xb4, 0xcc, 0x8a, 0xdc, 0x56, 0x1f, 0x92, 0xd0, 0xba, 0x7b, 0x73, 0xaa, 0xee, 0xdb, 0x49, 0xf3,
	0x0a, 0x4c, 0x22, 0xa3, 0xdd, 0x20, 0x11, 0x24, 0xa5, 0x6a, 0x27, 0xd8, 0xe4, 0xea, 0xf3, 0xc7,
	0x75, 0x64, 0x46, 0xdc, 0xe4, 0xaa, 0xb7, 0xc4, 0xce, 0x30, 0x74, 0xc6, 0x17, 0x50, 0x59, 0x73,
	0xe3, 0x57, 0x0e, 0xaa, 0xc0, 0xad, 0xe3, 0xeb, 0xd6, 0x6b, 0x39, 0xbf, 0x62, 0x77, 0xed, 0xef,
	0x40, 0x98, 0xc0, 0x6f, 0xbd, 0xfe, 0xf2, 0xe3, 0xed, 0xc2, 0x2a, 0xae, 0x13, 0x9b, 0xfd, 0x60,
	0xb5, 0xf8, 0x9d, 0x83, 0x2e, 0xcf, 0x5e, 0x3e, 0x26, 0xf3, 0x19, 0xac, 0x06, 0x70, 0x6f, 0xfd,
	0x7b, 0x81, 0x91, 0xe6, 0x6b, 0x69, 0x0d, 0xec, 0x5a, 0xa5, 0xe9, 0x8d, 0xe3, 0x4f, 0x0e, 0x5a,
	0x3a, 0xbb, 0x1d, 0xdc, 0x9e, 0x4f, 0x35, 0xc7, 0x19, 0x6e, 0xe7, 0x7f, 0x4a, 0x8c, 0xbe, 0xfb,
	0x5a, 0xdf, 0x5d, 0x7c, 0xc7, 0xaa, 0xef, 0x9c, 0x2f, 0xc8, 0x81, 0x31, 0xdb, 0x21, 0x39, 0xd0,
	0xf6, 0x3a, 0xec, 0x3e, 0x3c, 0x1a, 0x7b, 0xce, 0xf1, 0xd8, 0x73, 0xbe, 0x8f, 0x3d, 0xe7, 0xcd,
	0xc4, 0x2b, 0x1d, 0x4f, 0xbc, 0xd2, 0xd7, 0x89, 0x57, 0x7a, 0x11, 0xc4, 0x89, 0xda, 0x19, 0xf4,
	0x83, 0x50, 0xa4, 0x45, 0x77, 0x78, 0xad, 0xcb, 0x68, 0x97, 0xbc, 0x3c, 0x45, 0xa5, 0x46, 0x19,
	0x93, 0xfd, 0x8a, 0xfe, 0xe1, 0x6f, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x01, 0x2d, 0xc6,
	0xaf, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the current demurrage module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// DemurrageState returns the current module-level dynamic state
	// (current annual rate and global accumulator).
	DemurrageState(ctx context.Context, in *QueryDemurrageStateRequest, opts ...grpc.CallOption) (*QueryDemurrageStateResponse, error)
	// EffectiveBalance returns the post-demurrage (materialised) balance
	// for a given account address and denom.
	EffectiveBalance(ctx context.Context, in *QueryEffectiveBalanceRequest, opts ...grpc.CallOption) (*QueryEffectiveBalanceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.demurrage.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DemurrageState(ctx context.Context, in *QueryDemurrageStateRequest, opts ...grpc.CallOption) (*QueryDemurrageStateResponse, error) {
	out := new(QueryDemurrageStateResponse)
	err := c.cc.Invoke(ctx, "/cosmos.demurrage.v1.Query/DemurrageState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EffectiveBalance(ctx context.Context, in *QueryEffectiveBalanceRequest, opts ...grpc.CallOption) (*QueryEffectiveBalanceResponse, error) {
	out := new(QueryEffectiveBalanceResponse)
	err := c.cc.Invoke(ctx, "/cosmos.demurrage.v1.Query/EffectiveBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the current demurrage module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// DemurrageState returns the current module-level dynamic state
	// (current annual rate and global accumulator).
	DemurrageState(context.Context, *QueryDemurrageStateRequest) (*QueryDemurrageStateResponse, error)
	// EffectiveBalance returns the post-demurrage (materialised) balance
	// for a given account address and denom.
	EffectiveBalance(context.Context, *QueryEffectiveBalanceRequest) (*QueryEffectiveBalanceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DemurrageState(ctx context.Context, req *QueryDemurrageStateRequest) (*QueryDemurrageStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemurrageState not implemented")
}
func (*UnimplementedQueryServer) EffectiveBalance(ctx context.Context, req *QueryEffectiveBalanceRequest) (*QueryEffectiveBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EffectiveBalance not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.demurrage.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DemurrageState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDemurrageStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DemurrageState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.demurrage.v1.Query/DemurrageState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DemurrageState(ctx, req.(*QueryDemurrageStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EffectiveBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEffectiveBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EffectiveBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.demurrage.v1.Query/EffectiveBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EffectiveBalance(ctx, req.(*QueryEffectiveBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.demurrage.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DemurrageState",
			Handler:    _Query_DemurrageState_Handler,
		},
		{
			MethodName: "EffectiveBalance",
			Handler:    _Query_EffectiveBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/demurrage/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDemurrageStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDemurrageStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDemurrageStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDemurrageStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDemurrageStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDemurrageStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEffectiveBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEffectiveBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEffectiveBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEffectiveBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEffectiveBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEffectiveBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.EffectiveBalance.Size()
		i -= size
		if _, err := m.EffectiveBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDemurrageStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDemurrageStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEffectiveBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEffectiveBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EffectiveBalance.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDemurrageStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDemurrageStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDemurrageStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDemurrageStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDemurrageStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDemurrageStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEffectiveBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEffectiveBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEffectiveBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEffectiveBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEffectiveBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEffectiveBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EffectiveBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
